/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-explicit-any */
import Head from "next/head";
import Link from "next/link";
import { Gradient } from '../components/Gradient'
import { useEffect } from "react";
import { GradientGenerator } from "~/components/GradientGenerator/GradientGenerator";

// Create your instance


export default function Home() {
  const gradient = new Gradient()

// Call `initGradient` with the selector to your canvas
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          
          <GradientGenerator />
        </div>
      </main>
    </>
  );
}
